package org.doubango.imsdroid.events;

public enum RegistrationEventTypes {
	REGISTRATION_OK,
	REGISTRATION_NOK,
	REGISTRATION_INPROGRESS,
	UNREGISTRATION_OK,
	UNREGISTRATION_NOK,
	UNREGISTRATION_INPROGRESS
}
