package org.doubango.imsdroid.events;

public enum RegistrationEventTypes {
	REGISTRATION_CANCELLED,
    REGISTRATION_FAILED,
    REGISTRATION_FAILED_AUTHENTICATION,
    REGISTRATION_FAILED_TRANSPORT,
    REGISTRATION_FAILED_SECAGREE,
    REGISTRATION_NO_REPLY,
    REGISTRATION_OK,
    REGISTRATION_SENT,
    REGISTRATION_UNREGISTERED,
    REGISTRATION_UNREG_NETWORK_INIATED
}
