package org.doubango.imsdroid.events;

public enum SubscriptionEventTypes {
	SUBSCRIPTION_OK,
	SUBSCRIPTION_NOK,
	SUBSCRIPTION_INPROGRESS,
	UNSUBSCRIPTION_OK,
	UNSUBSCRIPTION_NOK,
	UNSUBSCRIPTION_INPROGRESS,
	INCOMING_NOTIFY
}
