/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.tinyWRAP;

public enum tsip_event_code_t {
  tsip_event_code_transport_error(702),
  tsip_event_code_global_error(703),
  tsip_event_code_message_error(704),
  tsip_event_code_request_incoming(800),
  tsip_event_code_request_cancelled(801),
  tsip_event_code_request_sent(802),
  tsip_event_code_dialog_terminated(900),
  tsip_event_code_dialog_connected(901),
  tsip_event_code_dialog_terminating(902);

  public final int swigValue() {
    return swigValue;
  }

  public static tsip_event_code_t swigToEnum(int swigValue) {
    tsip_event_code_t[] swigValues = tsip_event_code_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (tsip_event_code_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + tsip_event_code_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private tsip_event_code_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private tsip_event_code_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private tsip_event_code_t(tsip_event_code_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

